apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  namespace: httpbin-demo
  labels:
    app: httpbin
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-nodeport
  namespace: httpbin-demo
  labels:
    app: httpbin
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: httpbin